### ISSUE TITLE
Http Status Code 429 & 500 after Release v16.02.04

### ISSUE THREAD

**Issue by ALERTua** [Arcitectus/Sanderling#3]
After Release v16.02.04, licence requests fail with exceptions:

{Type:"System.Net.WebException",Message:"The remote server returned an error: (429).",InnerException:null,StackTrace:"   at System.Net.WebClient.UploadDataInternal(Uri address, String method, Byte[] data, WebRequest& request)
   at System.Net.WebClient.UploadData(Uri address, String method, Byte[] data)
   at System.Net.WebClient.UploadData(String address, String method, Byte[] data)
   at BotEngine.Interface.LicenseClient.UploadData(String Uri, Byte[] UploadData)
   at BotEngine.Interface.LicenseClient.UploadDataDeflate(String Uri, Byte[] UploadData)
   at BotEngine.Interface.LicenseClient.HttpExchangeLocked[TRequest,TResponse](String UriComponent, TRequest Request, Boolean Deflate)",TargetSite:"UploadDataInternal"}

and 500 (InternalServerError)
{Type:"System.Net.WebException",Message:"The remote server returned an error: (500) Internal Server Error.",InnerException:null,StackTrace:"   at System.Net.WebClient.UploadDataInternal(Uri address, String method, Byte[] data, WebRequest& request)
   at System.Net.WebClient.UploadData(Uri address, String method, Byte[] data)
   at System.Net.WebClient.UploadData(String address, String method, Byte[] data)
   at BotEngine.Interface.LicenseClient.UploadData(String Uri, Byte[] UploadData)
   at BotEngine.Interface.LicenseClient.UploadDataDeflate(String Uri, Byte[] UploadData)
   at BotEngine.Interface.LicenseClient.HttpExchangeLocked[TRequest,TResponse](String UriComponent, TRequest Request, Boolean Deflate)",TargetSite:"UploadDataInternal"}

**Comment by ALERTua** [comment]
using previous version crashes at application start with:
---------------------------
System.IO.FileNotFoundException
---------------------------
{Type:"System.IO.FileNotFoundException",Message:"Could not load file or assembly 'System.IO.FileSystem, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.",InnerException:null,StackTrace:"   at Microsoft.CodeAnalysis.Scripting.Hosting.GacFileResolver.Resolve(String assemblyName)

   at Microsoft.CodeAnalysis.Scripting.Hosting.RuntimeMetadataReferenceResolver.ResolveReference(String reference, String baseFilePath, MetadataReferenceProperties properties)

   at Microsoft.CodeAnalysis.CommonReferenceManager`2.ResolveReferenceDirective(String reference, Location location, TCompilation compilation)

   at Microsoft.CodeAnalysis.CommonReferenceManager`2.GetCompilationReferences(TCompilation compilation, DiagnosticBag diagnostics, ImmutableArray`1& references, IDictionary`2& boundReferenceDirectives, ImmutableArray`1& referenceDirectiveLocations)

   at Microsoft.CodeAnalysis.CommonReferenceManager`2.ResolveMetadataReferences(TCompilation compilation, ImmutableArray`1& references, IDictionary`2& boundReferenceDirectiveMap, ImmutableArray`1& boundReferenceDirectives, ImmutableArray`1& assemblies, ImmutableArray`1& modules, DiagnosticBag diagnostics)

   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.ReferenceManager.CreateAndSetSourceAssemblyFullBind(CSharpCompilation compilation)

   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.ReferenceManager.CreateSourceAssemblyForCompilation(CSharpCompilation compilation)

   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.GetDiagnostics(CompilationStage stage, Boolean includeEarlierStages, CancellationToken cancellationToken)

   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.GetDiagnostics(CancellationToken cancellationToken)

   at BotScript.UI.Wpf.Extension.<>c__DisplayClass3_0.<StatusIcon>b__0(DiagnosticSeverity Severity) in T:\\Günta\\Projekt\\BotScript\\Impl\\BotScript\\src\\BotScript.UI\\Wpf\\Extension.cs:line 73

   at BotScript.UI.Wpf.Extension.StatusIcon(Compilation Compilation) in T:\\Günta\\Projekt\\BotScript\\Impl\\BotScript\\src\\BotScript.UI\\Wpf\\Extension.cs:line 75

   at BotScript.UI.Wpf.IDE.Present() in T:\\Günta\\Projekt\\BotScript\\Impl\\BotScript\\src\\BotScript.UI\\Wpf\\IDE.xaml.cs:line 182

   at Sanderling.Exe.App.UIPresentScript()

   at Sanderling.Exe.App.Timer_Tick(Object sender, Object e)

   at System.Windows.Threading.DispatcherTimer.FireTick(Object unused)

   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)

   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)",TargetSite:"Resolve"}
---------------------------
OK   
---------------------------

**Comment by Arcitectus** [comment]
> After Release v16.02.04, licence requests fail with exceptions

This could be due to an existing configuration file which stored the old license server address. Please test only with the executable file.

**Comment by ALERTua** [comment]
deleting "config" file fixed the problem. thank you!
