### ISSUE TITLE
Concurrency exceptions

### ISSUE THREAD

**Issue by asdfasdf100500** [Arcitectus/Sanderling#4]
Hello

Roughly once per two days, I get these kind of exceptions:

`{Type:"System.InvalidOperationException",Message:"Collection was modified after the enumerator was instantiated.",InnerException:null,StackTrace:"   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.Queue`1.Enumerator.MoveNext()
   at System.Linq.Enumerable.LastOrDefault[TSource](IEnumerable`1 source)
   at Sanderling.Exe.App.get_FromMotionExecutionMemoryMeasurementTimeMin()
   at Sanderling.Exe.App.get_MeasurementRecentEnoughTime()
   at Sanderling.Exe.App.get_RequestedMeasurementTime()
   at Sanderling.Exe.App.InterfaceExchange()
   at Sanderling.Exe.App.Timer_Tick(Object sender, Object e)
   at System.Windows.Threading.DispatcherTimer.FireTick(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)",TargetSite:"ThrowInvalidOperationException"}`

Br. Asdf

**Comment by Arcitectus** [comment]
I recently fixed a bug which caused this exception: 130769829b8d05eee7df07d142abcb186af73375

release v16.03.09 contains the fix: https://github.com/Arcitectus/Sanderling/releases/tag/v16.03.09
